import "./PrivacyNotice.css"


const PrivacyNotice = (props) => {


    return (
        <div className="privacy-notice">
            <div className="privacy-wrapper">
                <h1>Privacy Notice</h1>
                <ol>
                    <li>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis atque molestiae dolorum reiciendis velit id, nostrum nihil! Itaque aspernatur velit enim blanditiis ipsam temporibus, recusandae pariatur nulla sapiente ratione, provident beatae consectetur quo, asperiores aut dolorum laudantium eius modi. Soluta officiis dolorum, corrupti repellat nam, eligendi voluptate eaque explicabo accusamus nostrum illum maxime ab sequi facere molestiae sunt in reprehenderit magnam, vitae tempore animi? Beatae, nostrum. Saepe iste nihil neque voluptas, pariatur expedita earum ullam enim doloremque ipsam quis dolorem excepturi harum dolorum quam vero totam. Sunt consequuntur delectus laudantium itaque cum voluptatibus iusto earum nulla dolore, nostrum nesciunt at exercitationem consectetur beatae commodi illum. Saepe quia fuga vitae sed, optio assumenda aut incidunt quae, ipsa qui error ut vero quo voluptas architecto ab dolorem recusandae. Cum voluptatem quis numquam, exercitationem soluta asperiores saepe, dolorem error magnam, obcaecati ratione facilis! Quos odit magnam possimus. Autem, totam voluptatem. Dignissimos, assumenda magni! Expedita, quaerat. Delectus quaerat adipisci corporis quidem impedit ad? Soluta, ab? Natus obcaecati doloribus aliquid magni! Molestias repudiandae quia, nam sunt cum inventore libero. Perferendis modi quos minus sapiente voluptate voluptas rem laboriosam, ipsum officiis quibusdam aut inventore tenetur nulla? Consectetur, nostrum facere. Debitis impedit consequuntur accusamus beatae doloremque nulla nostrum magni quasi nihil quisquam excepturi, sunt odit aspernatur nobis eius inventore quaerat assumenda, officiis dolorum voluptates? Voluptates, sint reprehenderit maiores ab ipsa velit. Hic mollitia repellat nisi modi officia fuga officiis praesentium minima expedita aliquam? Eveniet enim placeat accusantium ea corporis commodi tempore quasi reiciendis doloribus mollitia. Quis nulla cupiditate excepturi rerum sequi exercitationem facilis iste, quasi, possimus enim amet, laboriosam expedita qui sapiente atque magnam voluptates nam maxime? Ullam eum ipsa minus blanditiis voluptatum, vero rerum exercitationem, laboriosam unde saepe distinctio a pariatur autem neque. Quia iste aperiam labore ipsa repudiandae facere? Quos nostrum minima inventore excepturi odio.</p>
                    </li>
                    <li>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis atque molestiae dolorum reiciendis velit id, nostrum nihil! Itaque aspernatur velit enim blanditiis ipsam temporibus, recusandae pariatur nulla sapiente ratione, provident beatae consectetur quo, asperiores aut dolorum laudantium eius modi. Soluta officiis dolorum, corrupti repellat nam, eligendi voluptate eaque explicabo accusamus nostrum illum maxime ab sequi facere molestiae sunt in reprehenderit magnam, vitae tempore animi? Beatae, nostrum. Saepe iste nihil neque voluptas, pariatur expedita earum ullam enim doloremque ipsam quis dolorem excepturi harum dolorum quam vero totam. Sunt consequuntur delectus laudantium itaque cum voluptatibus iusto earum nulla dolore, nostrum nesciunt at exercitationem consectetur beatae commodi illum. Saepe quia fuga vitae sed, optio assumenda aut incidunt quae, ipsa qui error ut vero quo voluptas architecto ab dolorem recusandae. Cum voluptatem quis numquam, exercitationem soluta asperiores saepe, dolorem error magnam, obcaecati ratione facilis! Quos odit magnam possimus. Autem, totam voluptatem. Dignissimos, assumenda magni! Expedita, quaerat. Delectus quaerat adipisci corporis quidem impedit ad? Soluta, ab? Natus obcaecati doloribus aliquid magni! Molestias repudiandae quia, nam sunt cum inventore libero. Perferendis modi quos minus sapiente voluptate voluptas rem laboriosam, ipsum officiis quibusdam aut inventore tenetur nulla? Consectetur, nostrum facere. Debitis impedit consequuntur accusamus beatae doloremque nulla nostrum magni quasi nihil quisquam excepturi, sunt odit aspernatur nobis eius inventore quaerat assumenda, officiis dolorum voluptates? Voluptates, sint reprehenderit maiores ab ipsa velit. Hic mollitia repellat nisi modi officia fuga officiis praesentium minima expedita aliquam? Eveniet enim placeat accusantium ea corporis commodi tempore quasi reiciendis doloribus mollitia. Quis nulla cupiditate excepturi rerum sequi exercitationem facilis iste, quasi, possimus enim amet, laboriosam expedita qui sapiente atque magnam voluptates nam maxime? Ullam eum ipsa minus blanditiis voluptatum, vero rerum exercitationem, laboriosam unde saepe distinctio a pariatur autem neque. Quia iste aperiam labore ipsa repudiandae facere? Quos nostrum minima inventore excepturi odio.</p>
                    </li>
                    <li>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis atque molestiae dolorum reiciendis velit id, nostrum nihil! Itaque aspernatur velit enim blanditiis ipsam temporibus, recusandae pariatur nulla sapiente ratione, provident beatae consectetur quo, asperiores aut dolorum laudantium eius modi. Soluta officiis dolorum, corrupti repellat nam, eligendi voluptate eaque explicabo accusamus nostrum illum maxime ab sequi facere molestiae sunt in reprehenderit magnam, vitae tempore animi? Beatae, nostrum. Saepe iste nihil neque voluptas, pariatur expedita earum ullam enim doloremque ipsam quis dolorem excepturi harum dolorum quam vero totam. Sunt consequuntur delectus laudantium itaque cum voluptatibus iusto earum nulla dolore, nostrum nesciunt at exercitationem consectetur beatae commodi illum. Saepe quia fuga vitae sed, optio assumenda aut incidunt quae, ipsa qui error ut vero quo voluptas architecto ab dolorem recusandae. Cum voluptatem quis numquam, exercitationem soluta asperiores saepe, dolorem error magnam, obcaecati ratione facilis! Quos odit magnam possimus. Autem, totam voluptatem. Dignissimos, assumenda magni! Expedita, quaerat. Delectus quaerat adipisci corporis quidem impedit ad? Soluta, ab? Natus obcaecati doloribus aliquid magni! Molestias repudiandae quia, nam sunt cum inventore libero. Perferendis modi quos minus sapiente voluptate voluptas rem laboriosam, ipsum officiis quibusdam aut inventore tenetur nulla? Consectetur, nostrum facere. Debitis impedit consequuntur accusamus beatae doloremque nulla nostrum magni quasi nihil quisquam excepturi, sunt odit aspernatur nobis eius inventore quaerat assumenda, officiis dolorum voluptates? Voluptates, sint reprehenderit maiores ab ipsa velit. Hic mollitia repellat nisi modi officia fuga officiis praesentium minima expedita aliquam? Eveniet enim placeat accusantium ea corporis commodi tempore quasi reiciendis doloribus mollitia. Quis nulla cupiditate excepturi rerum sequi exercitationem facilis iste, quasi, possimus enim amet, laboriosam expedita qui sapiente atque magnam voluptates nam maxime? Ullam eum ipsa minus blanditiis voluptatum, vero rerum exercitationem, laboriosam unde saepe distinctio a pariatur autem neque. Quia iste aperiam labore ipsa repudiandae facere? Quos nostrum minima inventore excepturi odio.</p>
                    </li>
                </ol>
            </div>
        </div>
    )
}


export default PrivacyNotice